### ISSUE TITLE
Unknown plugin "@babel/proposal-class-properties" on version 2.0.2

### ISSUE THREAD

**Issue by danferd** [noelyoo/react-native-timer-countdown#12]
Getting this error when trying to sign the apk

TransformError: ../node_modules/react-native-timer-countdown/index.js: Unknown plugin "@babel/proposal-class-properties" specified in "../node_modules/react-native-timer-countdown/.babelrc" at 0, attempted to resolve relative to "../node_modules/react-native-timer-countdown"

**Comment by noelyoo** [comment]
@danferd I will check it out. Before that you might want to downgrade.

**Comment by noelyoo** [comment]
@danferd 
I made simple working example and generated signed the APK with it.
Check this out: https://github.com/noelyoo/react-native-timer-countdown-example

Also, I found some possibly relevant cases here:
https://github.com/react-community/react-native-maps/issues/1258

**Comment by noelyoo** [comment]
@danferd Thank you for letting me know the build issues.
the issue is fixed at https://github.com/noelyoo/react-native-timer-countdown/commit/ad5c1d2207537501a746a2d10143e26a97976309

Now version 2.0.3 published.
you can check the working example here: https://github.com/noelyoo/react-native-timer-countdown-example

**Comment by danferd** [comment]
Great. Thank you.
